// <auto-generated />
using System;
using ApptmentmentScheduler.DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApptmentmentScheduler.DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230823083756_seededdataintoDB")]
    partial class seededdataintoDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("ApptmentmentScheduler.Models.Models.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateTime = new DateTime(2023, 8, 23, 9, 37, 56, 45, DateTimeKind.Local).AddTicks(9823),
                            Description = "Meet with the Marketing team",
                            Name = "Abu Ghalib"
                        },
                        new
                        {
                            Id = 2L,
                            DateTime = new DateTime(2023, 8, 23, 9, 37, 56, 45, DateTimeKind.Local).AddTicks(9835),
                            Description = "Meeting with CEO Of LexCorp",
                            Name = "john"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
